#!/usr/bin/env bash

if
  [[ -s "/home/sirmmy/.rvm/rubies/ruby-2.7.4/lib/ruby/gems/2.7.0/environment" ]]
then
  source "/home/sirmmy/.rvm/rubies/ruby-2.7.4/lib/ruby/gems/2.7.0/environment"
  exec racc "$@"
else
  echo "ERROR: Missing RVM environment file: '/home/sirmmy/.rvm/rubies/ruby-2.7.4/lib/ruby/gems/2.7.0/environment'" >&2
  exit 1
fi
