#!/usr/bin/env bash

if
  [[ -s "/home/sirmmy/.rvm/gems/ruby-2.7.4/environment" ]]
then
  source "/home/sirmmy/.rvm/gems/ruby-2.7.4/environment"
  exec learn-status "$@"
else
  echo "ERROR: Missing RVM environment file: '/home/sirmmy/.rvm/gems/ruby-2.7.4/environment'" >&2
  exit 1
fi
